packages:
  - 'packages/*'

catalogMode: strict

# catalog:
catalog:
    "@babel/cli": 7.28.6
    next: 16.1.6
    react: 19.2.4
    react-dom: 19.2.4

catalogs:
  # catalog:peers
  peers:
    next: 16.x
    react: 18.x || 19.x
    react-dom: 18.x || 19.x

  # catalog:lint
  lint:
    "@eslint/js": 9.35.0
    "@next/eslint-plugin-next": 16.1.6
    eslint: 9.35.0
    eslint-config-next: 16.1.6
    eslint-plugin-jsx-a11y: 6.10.2
    eslint-plugin-react: 7.37.5
    eslint-plugin-react-hooks: 7.0.1
    globals: 17.4.0

  # catalog:test
  test:
    "@testing-library/dom": 10.4.1
    "@testing-library/jest-dom": 6.9.1
    "@testing-library/react": 16.3.2
    "@testing-library/user-event": 14.6.1
    babel-jest: 30.2.0
    jest: 30.2.0
    jest-environment-jsdom: 30.2.0
    jest-mock: 30.2.0
    msw: 2.12.10
    msw-storybook-addon: 2.0.6

  # catalog:storybook-modern
  storybook-modern:
    "@chromatic-com/storybook": 5.0.1
    "@storybook/addon-docs": 10.2.15
    "@storybook/addon-onboarding": 10.2.15
    "@storybook/addon-webpack5-compiler-swc": 4.0.2
    "@storybook/nextjs": 10.2.15
    "@storybook/react-webpack5": 10.2.15
    storybook: 10.2.15

  # catalog:storybook-html
  storybook-html:
    "@chromatic-com/storybook": 3.2.4
    "@storybook/addon-docs": 8.6.14
    "@storybook/addon-webpack5-compiler-swc": 2.1.0
    "@storybook/html": 8.6.14
    "@storybook/html-webpack5": 8.6.14
    "@storybook/test": 8.6.14
    storybook: 8.6.14
