packages:
  - 'packages/*'

# catalog:
catalog:
    next: ^15.1.7
    react: 18.3.1
    react-dom: 18.3.1

catalogs:
  # catalog:peers
  peers:
    next: 15.x
    react: 18.x || 19.x
    react-dom: 18.x || 19.x

  # catalog:build
  build:
    "@babel/cli": ^7.26.4
    babel-jest: ^29.7.0
    babel-loader: ^9.2.1
    clean-webpack-plugin: ^4.0.0
    webpack: ^5.98.0
    webpack-cli: ^6.0.1

  # catalog:test
  test:
    jest: ^29.7.0
    jest-environment-jsdom: ^29.7.0
    jest-mock: ^29.7.0
    msw: ^2.7.0
    msw-storybook-addon: ^2.0.4

  # catalog:storybook
  storybook:
    "@chromatic-com/storybook": ^3.2.4
    "@storybook/addon-essentials": ^8.5.6
    "@storybook/addon-interactions": ^8.5.6
    "@storybook/addon-onboarding": ^8.5.6
    "@storybook/addon-webpack5-compiler-swc": ^2.1.0
    "@storybook/blocks": ^8.5.6
    "@storybook/test": ^8.5.6
    storybook: ^8.5.6
