packages:
  - 'packages/*'

# catalog:
catalog:
    "@babel/cli": 7.26.4
    next: 15.1.7
    react: 19.0.0
    react-dom: 19.0.0

catalogs:
  # catalog:peers
  peers:
    next: 15.x
    react: 18.x || 19.x
    react-dom: 18.x || 19.x

  # catalog:test
  test:
    "@testing-library/dom": 10.4.0
    "@testing-library/jest-dom": 6.5.0
    "@testing-library/react": 16.0.0
    "@testing-library/user-event": 14.5.2
    babel-jest: 29.7.0
    jest: 29.7.0
    jest-environment-jsdom: 29.7.0
    jest-mock: 29.7.0
    msw: 2.7.0
    msw-storybook-addon: 2.0.4

  # catalog:storybook
  storybook:
    "@chromatic-com/storybook": 3.2.4
    "@storybook/addon-essentials": 8.5.8
    "@storybook/addon-interactions": 8.5.8
    "@storybook/addon-onboarding": 8.5.8
    "@storybook/addon-webpack5-compiler-swc": 2.1.0
    "@storybook/blocks": 8.5.8
    "@storybook/test": 8.5.8
    storybook: 8.5.8
