export { default as isBrowser } from '@/isBrowser'
export { default as makeListeners } from '@/listeners'
export { default as makePerformanceObserver } from '@/performanceObserver'
export { default as makeFnProxy } from '@/makeFnProxy'
export { default as getGuid } from '@/getGuid'
export { default as getFrameworks } from '@/getFrameworks'
export { default as hasDocument } from '@/hasDocument'
export { default as makeStorage } from '@/storage'
export * from '@/keys'
